# Generated by Django 4.0.1 on 2022-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='completionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Completion_Rate', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'completion_rate',
            },
        ),
        migrations.CreateModel(
            name='labourMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('January', models.FloatField(blank=True, null=True)),
                ('February', models.FloatField(blank=True, null=True)),
                ('March', models.FloatField(blank=True, null=True)),
                ('April', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('June', models.FloatField(blank=True, null=True)),
                ('July', models.FloatField(blank=True, null=True)),
                ('August', models.FloatField(blank=True, null=True)),
                ('September', models.FloatField(blank=True, null=True)),
                ('October', models.FloatField(blank=True, null=True)),
                ('November', models.FloatField(blank=True, null=True)),
                ('December', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labour_master',
            },
        ),
        migrations.CreateModel(
            name='labourMasterAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('January', models.FloatField(blank=True, null=True)),
                ('February', models.FloatField(blank=True, null=True)),
                ('March', models.FloatField(blank=True, null=True)),
                ('April', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('June', models.FloatField(blank=True, null=True)),
                ('July', models.FloatField(blank=True, null=True)),
                ('August', models.FloatField(blank=True, null=True)),
                ('September', models.FloatField(blank=True, null=True)),
                ('October', models.FloatField(blank=True, null=True)),
                ('November', models.FloatField(blank=True, null=True)),
                ('December', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labour_master_aggregate',
            },
        ),
        migrations.CreateModel(
            name='materialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('January', models.FloatField(blank=True, null=True)),
                ('February', models.FloatField(blank=True, null=True)),
                ('March', models.FloatField(blank=True, null=True)),
                ('April', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('June', models.FloatField(blank=True, null=True)),
                ('July', models.FloatField(blank=True, null=True)),
                ('August', models.FloatField(blank=True, null=True)),
                ('September', models.FloatField(blank=True, null=True)),
                ('October', models.FloatField(blank=True, null=True)),
                ('November', models.FloatField(blank=True, null=True)),
                ('December', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_master',
            },
        ),
        migrations.CreateModel(
            name='materialMasterAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('January', models.FloatField(blank=True, null=True)),
                ('February', models.FloatField(blank=True, null=True)),
                ('March', models.FloatField(blank=True, null=True)),
                ('April', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('June', models.FloatField(blank=True, null=True)),
                ('July', models.FloatField(blank=True, null=True)),
                ('August', models.FloatField(blank=True, null=True)),
                ('September', models.FloatField(blank=True, null=True)),
                ('October', models.FloatField(blank=True, null=True)),
                ('November', models.FloatField(blank=True, null=True)),
                ('December', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_master_aggregate',
            },
        ),
    ]
