# Generated by Django 4.0.1 on 2022-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0003_masteraggregate_masteryearlytotal_requiredtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITableOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('January', models.FloatField(blank=True, null=True)),
                ('February', models.FloatField(blank=True, null=True)),
                ('March', models.FloatField(blank=True, null=True)),
                ('April', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('June', models.FloatField(blank=True, null=True)),
                ('July', models.FloatField(blank=True, null=True)),
                ('August', models.FloatField(blank=True, null=True)),
                ('September', models.FloatField(blank=True, null=True)),
                ('October', models.FloatField(blank=True, null=True)),
                ('November', models.FloatField(blank=True, null=True)),
                ('December', models.FloatField(blank=True, null=True)),
                ('Master_Total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_table_one',
            },
        ),
    ]
