# Generated by Django 4.0.1 on 2022-02-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0007_rename_april_aitableone_april_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completionrate',
            old_name='completion_ate',
            new_name='completion_rate',
        ),
        migrations.RenameField(
            model_name='labourmaster',
            old_name='system_sode',
            new_name='system_code',
        ),
    ]
