# Generated by Django 4.0.1 on 2022-02-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0008_rename_completion_ate_completionrate_completion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.FloatField(blank=True, null=True)),
                ('february', models.FloatField(blank=True, null=True)),
                ('march', models.FloatField(blank=True, null=True)),
                ('april', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('june', models.FloatField(blank=True, null=True)),
                ('july', models.FloatField(blank=True, null=True)),
                ('august', models.FloatField(blank=True, null=True)),
                ('september', models.FloatField(blank=True, null=True)),
                ('october', models.FloatField(blank=True, null=True)),
                ('november', models.FloatField(blank=True, null=True)),
                ('december', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graph_data',
            },
        ),
    ]
