# Generated by Django 4.0.1 on 2022-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0009_graphdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
