# Generated by Django 4.0.1 on 2022-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0010_graphdata_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
