# Generated by Django 4.0.1 on 2022-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0011_graphdata_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='yearlyGraphData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('systemcode', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'yearly_graph_data',
            },
        ),
    ]
