# Generated by Django 4.0.1 on 2022-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRCpredictor', '0013_yearlygraphdata_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='accuracyTolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('tolerance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accuracy_tolerance',
            },
        ),
    ]
